EXTRA_CFLAGS  := 
CFLAGS_file.o := 

obj-y += page_manager.o
obj-y += my_t02.o
obj-y += bg1.o
obj-y += main_page.o
obj-y += Sr04_page.o
obj-y += Camera_page.o
obj-y += At24c02_page.o
obj-y += DHT11_page.o
obj-y += Album_page.o
obj-y += Sg90_page.o
